baseurl = "https://lianeyue.github.io" # Hostname (and path) to the root.
title = "Liane Yue" # Site title.
theme = "coder" # Set the theme.
languagecode = "en-us" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.
publishDir = "lianeyue.github.io"

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # New add.

disqusShortname = "lianeyue" # Enable or disable Disqus.

[params] # theme parameters
    hello = "Hello! It's&nbsp;nice&nbsp;to&nbsp;meet&nbsp;you."
    about = "I&nbsp;daydream and&nbsp;design."
    whatsup = "Currently enabling technology transformation&nbsp;at&nbsp;[EY&nbsp;Advisory](https://www.ey.com/en_gl/advisory/technology-transformation)." # Primary title.
    daydreams = "**L'idée fixe:** cultivating digital innovation&nbsp;for&nbsp;social&nbsp;impact." #Subtitle.
    passions = "**Passion projects:** sewing, freelance illustration and&nbsp;screenwriting." # Subtitle.
    description = "Liane Yue" # Site description.
    keywords = "liane,lianeyue,blog,developer,design,personal" # Site keywords.
    avatarurl = "/images/avatar.jpg" # Contain the path of the optional avatar in the static folder.
    bgurl = "images/gradient.jpg" # Contain the path of the optional bg in the static folder.

    footercontent = [] # Add footer content
    fixedbarContent = [] # Add fixedbar content.
    fixedbarContentAfter = [] # Add fixedbar content after click.

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu Items
    itemscentered = true

    # RTL Support
    rtl = false

    snsShare = true # New add.

    thumbnail = "images/tn.png" # Default sns thumbnail.

    # Multilanguage Mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social Links
#[[params.social]]
#    name = "Github"
#    weight = 1
#    url = "https://github.com/lianeyue/"
#[[params.social]]
#    name = "Twitter"
#    weight = 2
#    url = "https://twitter.com/lianeyue/"
#[[params.social]]
#    name = "LinkedIn"
#    weight = 3
#    url = "https://www.linkedin.com/in/lianeyue/"

# Menu Links
[[menu.main]]
    name = "Projects"
    weight = 1
    url  = "projects"
[[menu.main]]
    name = "Writing"
    weight = 2
    url = "posts"
[[menu.main]]
    name = "Illustration"
    weight = 3
    url = "illustration"
[[menu.main]]
    name = "About"
    weight = 4
    url = "about"